### PR TITLE
Improvements

### PR DESCRIPTION
**Pull request by brechtvdv**
- Fallback when arrdeps have no stopSequence and maxStopSequence. (See #3)
- Works with JSON-LD input streams.
- Inbound context with parameter.
- Flag to load in MongoDB.

### CODE REVIEW

**Comment by pietercolpaert** [comment]
Program does exit now?

**Comment by brechtvdv** [comment]
Yes

**Comment by pietercolpaert** [comment]
Can this be merged?

**Comment by brechtvdv** [comment]
You have my permission ;)

**Pull request merged**
